# 使用Node.js官方镜像作为基础镜像
FROM node:14

# 设置工作目录。你的应用代码将会在这个目录下
WORKDIR /app

# 复制package.json和package-lock.json
COPY package*.json ./

# 安装依赖
RUN npm install

# 复制剩余的后端源代码到工作目录下
COPY . .

# 你的应用绑定的端口号
EXPOSE 3000

# 定义环境变量
ENV NODE_ENV=production

# 运行你的程序
CMD ["node", "server.js"]
