version: '3.8'

services:
  backend:
    image: <your-epic-username>/quirknotes_backend:latest
    ports:
      - "4000:4000"
    depends_on:
      - mongodb

  frontend:
    image: <your-epic-username>/quirknotes_frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

